# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `builder` gem.
# Please instead update this file by running `bin/tapioca gem builder`.

module ActiveSupport::DeprecatedNumericWithFormat
  # source://activesupport/7.0.4/lib/active_support/core_ext/numeric/deprecated_conversions.rb#5
  def to_s(format = T.unsafe(nil), options = T.unsafe(nil)); end
end

module ActiveSupport::NumericWithFormat
  # source://activesupport/7.0.4/lib/active_support/core_ext/numeric/conversions.rb#111
  def to_formatted_s(format = T.unsafe(nil), options = T.unsafe(nil)); end

  # source://activesupport/7.0.4/lib/active_support/core_ext/numeric/conversions.rb#111
  def to_fs(format = T.unsafe(nil), options = T.unsafe(nil)); end
end

# Enhance the Integer class with a XML escaped character conversion.
class Integer < ::Numeric
  include ::ActiveSupport::NumericWithFormat
  include ::ActiveSupport::DeprecatedNumericWithFormat
end

class Symbol
  include ::Comparable
end
