# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `shoulda` gem.
# Please instead update this file by running `bin/tapioca gem shoulda`.

# source://shoulda//lib/shoulda/version.rb#1
module Shoulda
  class << self
    # source://shoulda-context/2.0.0/lib/shoulda/context/autoload_macros.rb#38
    def autoload_macros(root, *dirs); end
  end
end

# source://shoulda//lib/shoulda/version.rb#2
Shoulda::VERSION = T.let(T.unsafe(nil), String)
