require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails
  - rubocop-sorbet

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - sorbet/rbi/**/*.rbi
    - db/schema.rb
    - bin/*
    - db/migrate/*good_job*.rb

Layout/LineLength:
  Exclude:
    - db/migrate/*.rb

Lint/MissingSuper:
  Exclude:
    - app/components/**/*

Metrics/AbcSize:
  Exclude:
    - db/migrate/*.rb

Metrics/MethodLength:
  Exclude:
    - db/migrate/*.rb

Minitest/MultipleAssertions:
  Max: 4

Style/AccessorGrouping:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Sorbet/ValidSigil:
  RequireSigilOnAllFiles: true
  SuggestedStrictness: strict
