require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails
  - rubocop-sorbet

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

Minitest/MultipleAssertions:
  Max: 4

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Sorbet/ValidSigil:
  RequireSigilOnAllFiles: true
  SuggestedStrictness: strict
