# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `CleanupDecompsJob`.
# Please instead update this file by running `bin/tapioca dsl CleanupDecompsJob`.

class CleanupDecompsJob
  class << self
    sig { returns(T.any(CleanupDecompsJob, FalseClass)) }
    def perform_later; end

    sig { returns(T.untyped) }
    def perform_now; end
  end
end
