# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `EstimatesComponent`.
# Please instead update this file by running `bin/tapioca dsl EstimatesComponent`.

class EstimatesComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
