# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `NotificationComponent`.
# Please instead update this file by running `bin/tapioca dsl NotificationComponent`.

class NotificationComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
