# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `UserInfoComponent`.
# Please instead update this file by running `bin/tapioca dsl UserInfoComponent`.

class UserInfoComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
