default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres

development:
  <<: *default
  host: localhost
  database: decompery_development

test:
  <<: *default
  host: localhost
  database: decompery_test

production:
  <<: *default
  database: decompery_production
  username: decompery
  password: <%= ENV["DECOMPERY_DATABASE_PASSWORD"] %>
