name: Code Quality

on:
  push:
    branches:
      - main

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  code_quality:
    uses: ./.github/workflows/code_quality.yml
  deploy:
    runs-on: ubuntu-latest
    needs: code_quality
    steps:
    - uses: actions/checkout@v3
    - uses: superfly/flyctl-actions/setup-flyctl@master
    - run: flyctl deploy --remote-only
    - uses: honeybadger-io/github-notify-deploy-action@v1
      with:
        api_key: ${{ secrets.HONEYBADGER_API_KEY }}
